# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='adopcion',
        ),
    ]
