# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('fecha_rescate', models.DateTimeField()),
            ],
        ),
    ]
