# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20170902_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inocuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(through='mascota.Inocuacion', to='mascota.Vacuna'),
        ),
        migrations.AddField(
            model_name='inocuacion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Mascota'),
        ),
        migrations.AddField(
            model_name='inocuacion',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Vacuna'),
        ),
    ]
