# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20170902_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inocuacion',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='inocuacion',
            name='vacuna',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(db_table='inocuacion', related_name='inocuacion', to='mascota.Vacuna'),
        ),
        migrations.DeleteModel(
            name='Inocuacion',
        ),
    ]
