# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20170901_2227'),
        ('mascota', '0009_remove_mascota_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duenio', to='adopcion.Persona'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(db_table='inocuacion', related_name='inocuacion', to='mascota.Vacuna'),
        ),
    ]
